name = "login-test"

[vars]
CLOUD_NAME= "duv7zmdkz"
CLOUD_KEY= "166311878598385"
CLOUD_SECRET= "MAdK2AQ-XE1VwC9-JNgqLjCM6e0"
REACT_APP_CLERK_PUBLISHABLE_KEY= "pk_test_aG9wZWZ1bC1zcGFuaWVsLTE4LmNsZXJrLmFjY291bnRzLmRldiQ"
REACT_APP_CLERK_SECRET_KEY= "sk_test_NUjYYxQVKy0DVj0vPgEcFWFORIQJYilZIJyVSeHTEX"


type = "javascript"
compatibility_date = "2024-09-26"
account_id = "756c633bf2948763f2ee715b68f92266"
workers_dev = true

[[kv_namespaces]] 
binding = "profit"
id = "3844523479c64024aa4aeafc5c8c3b9f" 



[site]
bucket = "./build"

