name = "login-test"
type = "javascript"
compatibility_date = "2024-09-26"

account_id = "756c633bf2948763f2ee715b68f92266"
workers_dev = true

[site]

bucket = "./build"

[[redirects]]
from = "your-domain.com/*"
to = "/index.html"
status = 200

[vars]
REACT_APP_CLERK_PUBLISHABLE_KEY= "pk_test_aG9wZWZ1bC1zcGFuaWVsLTE4LmNsZXJrLmFjY291bnRzLmRldiQ"
REACT_APP_CLERK_SECRET_KEY= "sk_test_NUjYYxQVKy0DVj0vPgEcFWFORIQJYilZIJyVSeHTEX"